tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "ansible"
brew "coreutils"
brew "asdf"
brew "docker-compose", link: false
brew "dockutil"
brew "fzf"
brew "gettext"
brew "ghq"
brew "gibo"
brew "git"
brew "gnupg"
brew "mas"
brew "pcre"
brew "peco"
brew "youtube-dl"
cask "alfred"
cask "appcleaner"
cask "authy"
cask "clipy"
cask "discord"
cask "docker"
cask "figma"
cask "firefox"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "karabiner-elements"
cask "skitch"
cask "slack"
cask "visual-studio-code"
cask "zoomus"
mas "1Password 7", id: 1333542190
mas "GIPHY CAPTURE", id: 668208984
